import Siderbar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
export const metadata = {
  title: "First App (Dashboard)",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children, // will be a page or nested layout
}) {
  return (
    <section>
      {/* Include shared UI here e.g. a header or sidebar */}
      <Navbar>Navbar</Navbar>
      <Siderbar>Sidebar</Siderbar>

      {children}
      <Footer>Footer</Footer>
    </section>
  );
}
